[package]
name = "hsb-to-hsl"
version = "0.1.0"
authors = ["lukethacoder <dev@lukesecomb.digital>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]