[package]
name = "sfdx-list"
version = "0.1.0"
authors = ["Luke Secomb <hello@lukesecomb.digital>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
regex = "1"
colored = "2"