[package]
name = "rust-playground-stuffs"
version = "0.1.0"
authors = ["Luke Secomb <luke.secomb@live.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
regex = "1"
colored = "2"