[package]
name = "github-api"
version = "0.1.0"
authors = ["lukethacoder <dev@lukesecomb.digital>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.10.0", features = ["blocking"]}
serde = { version = "1.0.104", features = ["derive"] }