[package]
name = "scraping-my-own-site"
version = "0.1.0"
authors = ["lukethacoder <dev@lukesecomb.digital>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soup = "0.4.1"
reqwest = "0.9.4"