[package]
name = "sfdx-open"
version = "0.1.0"
authors = ["Luke Secomb <hello@lukesecomb.digital>"]
edition = "2021"

[dependencies]
colored = "2"
async-std = {version = "1.10.0", features = ["attributes"]}